---
title: "Untitled"
author: "Léo"
date: "2023-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(forcats)
library(ggplot2)
library(rstan)
library(brms)
library(uwot)
```

# Load datasets
```{r}
df_PB = read.table('D:/playbacks/all_datasets/df_PB.csv', header = T, sep = ';', dec = ',')
```

```{r}
ag_bhv = read.table('D:/playbacks/all_datasets/ag_bhv.csv', header = T, sep =';', dec = ',')

# Create a data frame with all possible combinations of id, exp_type, and timeclass
all_combinations <- expand.grid(
  exp_id = unique(ag_bhv$exp_id),
  Behavior = unique(ag_bhv$Behavior),
  timeline = unique(ag_bhv$timeline)
)

# Merge the original data frame with the all_combinations data frame
# This will add missing rows with n = 0
result <- merge(all_combinations, ag_bhv, all.x = TRUE)

# Replace NA values in 'n' with 0
result$duration[is.na(result$duration)] <- 0

result$exp_id = as.character(result$exp_id)

for (i in 1:nrow(result)) {
  result$pb_type[i] = strsplit(result$exp_id[i], split = '_')[[1]][3]
}

# write.csv2(result, 'E:/fieldwork_2023/playbacks/results/ag_bhv_with_zeros2.csv', sep = '\t', dec = '.')
```

``` {r}
ag_PB = read.table('D:/playbacks/all_datasets/ag_PB.csv', header = T, sep =';', dec = ',')

ag_bhv = read.table('D:/playbacks/all_datasets/ag_bhv_with_zeros.csv', header = T, sep =';', dec = ',')


ag_bhv$duration[is.na(ag_bhv$duration)] <- 0
ag_bhv$diff[is.na(ag_bhv$diff)] <- 0
ag_bhv$perc_diff[is.na(ag_bhv$perc_diff)] <- 0
ag_bhv$dim[is.na(ag_bhv$dim)] <- 0

ag_bhv$mod = cut(ag_bhv$perc_diff,
                    breaks = c(-Inf, -0.25, 0.25, Inf),
                    labels = c(1,2,3))
ag_bhv$mod = as.numeric(ag_bhv$mod)

# remove playbacks with runaway
ag_bhv_no_runaway = subset(ag_bhv, !(exp_id %in% unique(df_PB$exp_id[df_PB$runaway == 'Yes'])))
ag_bhv$mod = as.numeric(ag_bhv_no_runaway$mod)

runaways = data.frame(pb_type = c('ctr', 'fam', 'nbg', 'str'), perc = c(0, 0, 1/15, 7/18), n = c("n = 0", "n = 0", "n = 1", "n = 7"))
```

# Number of runaways
```{r}
ggplot(data = runaways) +
  geom_bar(aes(x=pb_type, y=perc, fill = pb_type), stat="identity", alpha=0.7) +
 # geom_text(aes(label = n, x = pb_type, y = 0.0), hjust = -0.85)+
  theme_bw()+
  scale_x_discrete(labels = c('Control', 'Groupmate', 'Neighbor', 'Stranger'))+
  theme(panel.grid = element_blank()) +
  labs(y = 'Proportion of withdrawn\nindividuals following playback', x = 'Playback type')+
  ylim(0,0.5)+
  theme(legend.position = 'none') + 
  coord_flip()

ggsave("D:/playbacks/all_plots/withdraw.png", width = 3, height = 4)
```


# Change in number of vocs during playbacks

```{r}
# remove playbacks with runaway
ag_PB_no_runaway = subset(ag_PB, !(exp_id %in% unique(df_PB$exp_id[df_PB$runaway == 'Yes'])))

for (i in 1:nrow(ag_PB_no_runaway)) {
  ag_PB_no_runaway$diff[i] = 
    ag_PB_no_runaway$id[i] - ag_PB_no_runaway$id[ag_PB_no_runaway$timeline == "before" 
                                                 & ag_PB_no_runaway$exp_id == ag_PB_no_runaway$exp_id[i]]
  ag_PB_no_runaway$perc_diff[i] = 
    ag_PB_no_runaway$diff[i]/ag_PB_no_runaway$id[ag_PB_no_runaway$timeline == "before" 
                                                 & ag_PB_no_runaway$exp_id == ag_PB_no_runaway$exp_id[i]]
  ag_PB_no_runaway$dim = cut(ag_PB_no_runaway$diff,
                             breaks = c(-Inf, 0.1, Inf),
                             labels = c(0,1))
}

ag_PB_no_runaway$perc_diff[is.nan(ag_PB_no_runaway$perc_diff)] = 0
ag_PB_no_runaway$perc_diff[ag_PB_no_runaway$perc_diff == Inf] = 1 
ag_PB_no_runaway$perc_diff[ag_PB_no_runaway$perc_diff > 1] = 1 


hist(ag_PB_no_runaway$perc_diff[ag_PB$timeline != 'before'], breaks = 20)

# --------------------- MODEL BUILDING -----------------------------------
brm_type_timeline = brm(dim ~ pb_type * timeline, 
                     data = ag_PB_no_runaway[ag_PB_no_runaway$timeline != 'before',], family = 'bernoulli',
                     warmup = 200, iter = 2000, chains = 2, cores = 4,
                     file = 'F:/fieldwork_2023/playbacks/results/models/brm_type_nvocs_cum.rds')

# pp_check(brm_type_timeline)

# plot(conditional_effects(brm_type_timeline), points = F)
# ------------------------------------------------------------------------

# extract fitted values 

newdata = aggregate(perc_diff ~ pb_type + timeline, 
                    data = ag_PB_no_runaway[ag_PB_no_runaway$timeline != 'before',], FUN = length)
newdata = newdata[,c(1,2)]


fit_type_timeline = fitted(
  brm_type_timeline,
  newdata = newdata,
  re_formula = NA,
  robust = TRUE
)


pl_type_timeline = cbind(newdata, fit_type_timeline)
colnames(pl_type_timeline) = c('pb_type', 'timeline', 'fit', 'se', 'lwr', 'upr')


ggplot(data = pl_type_timeline[pl_type_timeline$timeline!='after',],
       aes(x = fit*100, y = pb_type, 
           xmin = lwr*100, xmax = upr*100, color = pb_type)) +
       geom_pointrange(stat = 'identity', position = position_dodge(0.4)) +
       scale_y_discrete(labels = c('Control', 'Groupmate', 'Neighbor', 'Stranger')) +
       labs(x = 'Percentage of chances to have an augmentation\nin number of vocs emmited / minute',
            y = '', color = 'Type of \nplayback')+
       coord_flip() +
       theme_bw() +
       theme(panel.grid = element_blank(),
             legend.position = 'none') +
       geom_vline(xintercept = 50, linetype = 2) +
       xlim(0,100)

# ggsave(filename = 'D:/playbacks/all_plots/model_pb_vocs.png', height = 4, width = 4)

# contrasts 

ctr_type_timeline = fitted(brm_type_timeline, newdata = newdata, re_formula = NA, robust = TRUE, summary = F)
d = ctr_type_timeline [,14] - ctr_type_timeline [,7]
q = round(quantile(d, c(0.025, 0.5, 0.975))*100, 2)
glue('{round(q[2], 2)}%, 95% CI [{round(q[1], 2)}%; {round(q[3], 2)}%]')

```
# raw number of diminution / increase 

```{r}
ag_PB_no_runaway$dim2 = as.numeric(ag_PB_no_runaway$dim)-1

ag_PB_raw = aggregate(dim2~pb_type, data = ag_PB_no_runaway[ag_PB_no_runaway$timeline=='playback',], FUN = sum)

ag_PB_raw_tot = aggregate(dim2~pb_type, data = ag_PB_no_runaway[ag_PB_no_runaway$timeline=='playback',], FUN = length)



```


#  Augmentation or diminution of time doing specific behaviors during playbacks


## all behavior - diff in seconds


```{r}
data_bhv = read.table('D:/playbacks/all_datasets/data_bhv_model_diff_in_s.csv', sep = ';', dec = '.', header = T)

# 1) 
hurdle_gaussian <- 
# Create a custom family that is logit if y = 0, normal/gaussian if not
  custom_family("hurdle_gaussian", 
                dpars = c("mu", "sigma", "hu"),
                links = c("identity", "log", "logit"),
                lb = c(NA, 0, NA),
                type = "real")

# 2)
# Stan code
stan_funs <- "
  real hurdle_gaussian_lpdf(real y, real mu, real sigma, real hu) { 
    if (y == 0) { 
      return bernoulli_lpmf(1 | hu); 
    } else { 
      return bernoulli_lpmf(0 | hu) +  
             normal_lpdf(y | mu, sigma); 
    } 
  }
"

# 3)
posterior_predict_hurdle_gaussian <- function(i, prep, ...) {
  mu <- brms::get_dpar(prep, "mu", i = i)
  sigma <- brms::get_dpar(prep, "sigma", i = i)
  theta <- brms::get_dpar(prep, "hu", i = i)

  hu <- runif(prep$ndraws, 0, 1)
  ifelse(hu < theta, 0, rnorm(prep$ndraws, mu,sigma))
}

posterior_epred_hurdle_gaussian <- function(prep) {
  with(prep$dpars, mu * (1 - hu))
}

# Prepare Stan code for use in brm()
stanvars <- stanvar(scode = stan_funs, block = "functions")


# -------------------  MODEL BUILDING  ----------------------------
brm_bhv_type = brms::brm(diff ~ Behavior * pb_type + (1|indiv), 
                     data = data_bhv,
                     family = hurdle_gaussian,
                     stanvars = stanvars,
                     warmup = 2000, iter = 10000, chains = 4, cores = 6,
                     file = 'D:/playbacks/all_models/brm_pbtype_all_diff_hurdle-gaussian_rdindiv.rds')

pp_check(brm_bhv_type, type = 'boxplot', ndraws = 20)
conditional_effects(brm_bhv_type)
# -------------------------------------------------------------------


```

```{r}
newdata = aggregate(perc_diff ~ pb_type + Behavior + timeline, 
                    data =  data_bhv, 
                    FUN = length)
newdata = newdata[,c(1,2)]

fit_bhv_type= fitted(brm_bhv_type, newdata = newdata,  re_formula = NA,  robust = TRUE,  summary = T)

pl_bhv_type = cbind(newdata, fit_bhv_type)
colnames(pl_bhv_type) = c('pb_type', 'behavior', 'fit', 'se', 'lwr', 'upr')
pl_bhv = pl_bhv_type


ggplot(pl_bhv, aes(x = fit, y = pb_type, xmin = lwr, xmax = upr, color = pb_type)) +
  geom_pointrange(stat = 'identity', position = position_dodge(0.4)) +
  labs(x = 'Difference compare to the\nminute before the playback (s)', y = '',  color = 'Type of \nplayback')+
  scale_y_discrete(labels = c('Control', 'Groupmate', 'Neighbor', 'Stranger'))+
  scale_color_discrete(labels = c('Control', 'Groupmate', 'Neighbor', 'Stranger')) +
  coord_flip() +
  theme_bw() +
  xlim(-35,45) +
  theme(panel.grid = element_blank()) +
  geom_vline(xintercept = 0, linetype = 2) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1.1))+
  theme(legend.position = 'bottom') +
  facet_grid(cols = vars(behavior))

# ggsave('D:/playbacks/all_plots/hurdle_gaussian_model_bhv_45-30.png', height = 6, width = 5)
```
# contrasts 

```{r}
df_ctr_bhv = data.frame(Basking = rep(NA, 4), Exploration = rep(NA, 4), Vigilance = rep(NA, 4), 
                        row.names = c("Control", "Groupmate", "Neighbor", "Stranger"))

pl_bhv_type

k = 1
j = 0
for (i in 1:nrow(pl_bhv_type)) {
  
  j = j+1
  df_ctr_bhv[j, k] =  glue('{round(pl_bhv_type$fit[i], 1)} s, [{round(pl_bhv_type$lwr[i], 1)} s, {round(pl_bhv_type$upr[i], 1)} s]')
  
  if (j %% 4 == 0) {
    j = 0
    k = k+1}

}

write.csv2(df_ctr_bhv, file = glue('D:/playbacks/all_tables/ctr_bhv.csv'))
```





# with lines 

```{r}
ag_bhv_no_runaway_lines = subset(ag_bhv_no_runaway, timeline != 'after' & Behavior != 'Nest')
ag_bhv_no_runaway_lines$id_mark = paste(ag_bhv_no_runaway_lines$exp_id, ag_bhv_no_runaway_lines$Behavior, ag_bhv_no_runaway_lines$timeline, sep = '_')

library(ggpattern)

pal = data.frame(pb_type = unique(mean_bhv$pb_type), col = c('#F8766D', '#7dae00', '#00bdc4', '#c77bff'))

for (i in unique(mean_bhv$Behavior)) {
  
  for (j in unique(mean_bhv$pb_type)) {
    
    ggplot(data = mean_bhv[mean_bhv$Behavior==i & mean_bhv$pb_type==j,], 
           aes(x = timeline,  y = duration, fill = pb_type, pattern = timeline, alpha = timeline)) +
    geom_bar(stat = 'identity', position = position_dodge(0.7), width = 1) +
    scale_alpha_manual(values = c(before = 0.5, playback = 1)) +
    scale_fill_manual(values = c(pal$col[pal$pb_type==j]))+
    guides(fill = guide_legend(override.aes = list(pattern = "none")))+
    geom_line(data = ag_bhv_no_runaway_lines[ag_bhv_no_runaway_lines$Behavior==i &  ag_bhv_no_runaway_lines$pb_type==j, ],  
                 aes(x = timeline, y = duration, group = exp_id), alpha = 1, size = 0.5, linetype = 2) +
    labs(x = 'Playback type', y = 'Mean time engaged in the behavior (s) ',  fill = 'Playback type', pattern = 'Time')+
    ylim(0,60) +
    theme(panel.grid = element_blank(),
          panel.background = element_blank(),
          axis.line.y = element_blank()) +
    theme(legend.position = 'none')
    
    plot(last_plot())
    
   ggsave(glue('D:/playbacks/all_plots/behavior/00noY_{i}_{j}.png'), width = 2, height = 5)
  }
  
}



```


